# compute_environment: LOCAL_MACHINE
# distributed_type: MULTI_GPU
# downcast_bf16: 'no'
# gpu_ids: all
# mixed_precision: 'no'
# num_machines: 1
# num_processes: 1
# rdzv_backend: static
# same_network: false
# tpu_env: []
# tpu_use_cluster: false
# tpu_use_sudo: false
# use_cpu: false

compute_environment: LOCAL_MACHINE
deepspeed_config:
 gradient_accumulation_steps: 1
 gradient_clipping: 1.0
 offload_optimizer_device: none
 offload_param_device: none
 zero3_init_flag: False
 zero_stage: 2
distributed_type: DEEPSPEED
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 5
use_cpu: false

# compute_environment: LOCAL_MACHINE
# deepspeed_config:
#   gradient_accumulation_steps: 1
#   gradient_clipping: 1.0
#   offload_optimizer_device: None
#   offload_param_device: None
#   zero3_init_flag: true
#   zero3_save_16bit_model: true
#   zero_stage: 3
# distributed_type: DEEPSPEED
# fsdp_config: {}
# machine_rank: 0
# main_process_ip: null
# main_process_port: null
# main_training_function: main
# mixed_precision: fp16
# num_machines: 1
# num_processes: 6
# use_cpu: false